"""Copy that exists only in the slide deck: narration, part headings, chips and
buttons, in both languages. Everything else on a slide comes from index.html or
index-zh.html unchanged.

LINES has one row per slide, in slide order: (key, mood, Kenji's line, Capy's
readout or None). The build fails if the rows fall out of step with the slides.
Moods are the face files in deck-img/kenji-<mood>.jpg.
"""

EN_FONTS = 'https://fonts.googleapis.com/css2?family=Bangers&family=Comic+Neue:wght@400;700&family=Space+Mono:wght@700&display=swap'
ZH_FONTS = 'https://fonts.googleapis.com/css2?family=Bangers&family=Comic+Neue:wght@400;700&family=Space+Mono:wght@700&family=ZCOOL+KuaiLe&display=swap'

T = {
 'en': dict(
    fonts=EN_FONTS, lang_from='/index-zh', lang_to='/deck-zh',
    css=':root{--comic:"Bangers","Archivo",sans-serif}',
    intro_acc='#e8b53a', anthem_label='Stay in the loop', contents='Contents',
    toc_intro='Why you should care', toc_end='Stay in the loop',
    intro_parts=['Welcome', 'Why care', 'Claim 1: it is arriving soon', 'Claim 2: the stakes', 'Claim 3: nobody knows how', 'The only solution'],
    back='Back', cont='Continue', cont_part='Continue to part %d', next='Next: %s', restart='Back to the start',
    chips_aria='Parts of this chapter', nav_aria='Slides', prev='Previous slide', next_aria='Next slide',
    keys='Use &larr; &rarr; keys', open_any=' Open any card to see how it would unfold.',
    kenji_alt='Kenji, looking %s',
    moods=dict(happy='happy', idea='like he has an idea', calm='calm', alarmed='alarmed', puzzled='puzzled',
               shocked='shocked', worried='worried', surprised='surprised', sad='sad', serious='serious'),
    parts={
      '2.1': ['The prize in numbers', 'Where people would feel it'],
      '2.2': ['Four ways it goes wrong', 'Why it would take what we need', 'Six paths to extinction'],
      '2.3': ['No second try', 'Reason 1: it is improving itself', 'Reason 2: the gap outruns us'],
      '3.1': ['The trap', 'Inside one lab'],
      '3.2': ['No shared values', 'Two layers of trust', 'Who decides'],
      '4.1': ['Two ways it fails', 'Outer alignment', 'Worded well, still wrong', 'See it happen', 'Inner alignment', 'What we can see'],
      '4.2': ['Why tests stop working', 'How the tests get beaten', 'What we cannot check'],
      '5.1': ['Four layers', 'Go further'],
      '5.2': ['Four hard cases', 'What survives'],
    },
    heads={
      '2.1b': ('Part 2 · Where people would feel it', 'Growth on that scale would reach almost every part of daily life',
               'The chart is about the whole economy. These six cards are about what it would change for a person.'),
      '2.2b': ('Part 2 · Why it would take what we need', 'A goal that has nothing to do with us can still cost us everything'),
      '2.2c': ('Part 3 · Six paths to extinction', 'Six paths, each one ending in extinction'),
      '2.3b': ('Part 2 · Reason 1 of 2', 'The first reason is that the loop has already started, and people are stepping out of it.'),
      '2.3c': 'Part 3 · Reason 2 of 2',
      '3.1b': ('Part 2 · Inside one lab', 'Every lab faces the same two pressures',
               'Going carefully means losing ground, and going fast puts everyone at risk. Read the two cards, then make the call yourself.'),
      '3.2b': ('Part 2 · Two layers of trust', 'Every hand-off needs trust twice, first in the builders and then in the system'),
      '3.2c': ('Part 3 · Who decides', 'The people choosing are a tiny slice of the people affected'),
      '4.1b': 'Part 2 · Outer alignment',
      '4.1c': 'Part 3 · Worded well, still wrong',
      '4.1d': 'Part 4 · See it happen',
      '4.1e': 'Part 5 · Inner alignment',
      '4.1f': 'Part 6 · What we can see',
      '4.2b': 'Part 2 · How the tests get beaten',
      '4.2c': 'Part 3 · What we cannot check',
      '5.1layer': 'Part %d · Layer %d of 4',
      '5.1f': 'Part 6 · Go further',
      '5.2b': 'Part 2 · What survives',
    },
    tries_title='Crash, fix, repeat', tries_legend=('Crash', 'Fix', 'Safe, eventually'),
    tries_norun='No practice run', tries_oneshot='One shot',
    tries_alt='Cars, planes and nuclear power each became safe through repeated crashes and fixes. AI has no practice run.',
    tries_rows=[
      ('Cars', [('f', 'car_crash', 'Crash'), ('x', 'seatbelt', 'Seatbelt ’59'), ('f', 'car_crash', 'Crash'), ('x', 'airbag', 'Airbag ’98'), ('s', 'safe_car', 'Safe')]),
      ('Planes', [('f', 'midair', 'Mid-air crash ’56'), ('x', 'tower', 'Air traffic control'), ('f', 'runway', 'Runway crash ’77'), ('x', 'crew', 'Crew training'), ('s', 'safe_plane', 'Safe')]),
      ('Nuclear', [('f', 'meltdown', 'Meltdown ’79'), ('x', 'inspect', 'Inspections'), ('f', 'meltdown', 'Chernobyl ’86'), ('x', 'peer', 'Peer review'), ('s', 'safe_plant', 'Safe')]),
    ],
 ),
 'zh': dict(
    fonts=ZH_FONTS, lang_from='/', lang_to='/deck',
    css=(':root{--comic:"Bangers","ZCOOL KuaiLe","PingFang SC","Microsoft YaHei",sans-serif;'
         '--body:"Comic Neue","PingFang SC","Hiragino Sans GB","Microsoft YaHei","Noto Sans SC",system-ui,sans-serif!important;'
         '--display:"Bangers","ZCOOL KuaiLe","PingFang SC","Microsoft YaHei",sans-serif!important}'
         '.t-more::before{content:"展开阅读"!important}.lx-open > .t-more::before{content:"收起"!important}'),
    intro_acc='#e8b53a', anthem_label='保持联系', contents='目录',
    toc_intro='我们为什么该在意', toc_end='保持联系',
    intro_parts=['欢迎', '为什么要在意', '论点一：它很快就会到来', '论点二：赌注极高', '论点三：没人知道怎么做', '唯一的出路'],
    back='返回', cont='继续', cont_part='继续看第 %d 部分', next='下一节：%s', restart='回到开头',
    chips_aria='本章的几个部分', nav_aria='翻页', prev='上一页', next_aria='下一页',
    keys='用 &larr; &rarr; 键翻页', open_any='点开任意一张卡片，看看它会怎样展开。',
    kenji_alt='Kenji，%s',
    moods=dict(happy='很开心', idea='想到了主意', calm='很平静', alarmed='很惊慌', puzzled='很困惑',
               shocked='很震惊', worried='很担心', surprised='很惊讶', sad='很难过', serious='很严肃'),
    parts={
      '2.1': ['用数字看回报', '人们会在哪里感受到它'],
      '2.2': ['四种出错方式', '它为何会夺走我们所需', '六条通往灭绝的路'],
      '2.3': ['没有第二次机会', '原因一：它在自我改进', '原因二：差距跑得比我们快'],
      '3.1': ['陷阱', '走进一家实验室'],
      '3.2': ['没有共同的价值观', '两重信任', '谁来决定'],
      '4.1': ['两种失败', '外部对齐', '写得再好，照样出错', '亲眼看看', '内部对齐', '我们能看见什么'],
      '4.2': ['测试为何失灵', '测试是怎样被钻空子的', '我们检验不了什么'],
      '5.1': ['四层防线', '深入了解'],
      '5.2': ['四个难点', '哪些扛得住'],
    },
    heads={
      '2.1b': ('第 2 部分 · 人们会在哪里感受到它', '这样规模的增长，几乎会触及日常生活的每个角落',
               '上面的图讲的是整个经济。这六张卡片讲的是，它会给一个人的生活带来什么变化。'),
      '2.2b': ('第 2 部分 · 它为何会夺走我们所需', '一个与我们毫不相干的目标，照样可能让我们失去一切'),
      '2.2c': ('第 3 部分 · 六条通往灭绝的路', '六条路，每一条都通向灭绝'),
      '2.3b': ('第 2 部分 · 原因一（共二）', '第一个原因是，这个循环已经开始，而人正在一步步退出其中。'),
      '2.3c': '第 3 部分 · 原因二（共二）',
      '3.1b': ('第 2 部分 · 走进一家实验室', '每家实验室都面对同样的两股压力',
               '走得谨慎就会落后，走得太快又会把所有人置于险境。读完这两张卡片，再自己做决定。'),
      '3.2b': ('第 2 部分 · 两重信任', '每一次托付都要信任两回，先信任建造者，再信任系统'),
      '3.2c': ('第 3 部分 · 谁来决定', '做选择的人，只占受影响者中极小的一部分'),
      '4.1b': '第 2 部分 · 外部对齐',
      '4.1c': '第 3 部分 · 写得再好，照样出错',
      '4.1d': '第 4 部分 · 亲眼看看',
      '4.1e': '第 5 部分 · 内部对齐',
      '4.1f': '第 6 部分 · 我们能看见什么',
      '4.2b': '第 2 部分 · 测试是怎样被钻空子的',
      '4.2c': '第 3 部分 · 我们检验不了什么',
      '5.1layer': '第 %d 部分 · 第 %d 层（共 4 层）',
      '5.1f': '第 6 部分 · 深入了解',
      '5.2b': '第 2 部分 · 哪些扛得住',
    },
    tries_title='出事，改进，再出事', tries_legend=('事故', '改进', '终于安全'),
    tries_norun='没有演练', tries_oneshot='只有一次',
    tries_alt='汽车、飞机和核电，都是在一次次事故和改进中才变得安全。AI 没有演练的机会。',
    tries_rows=[
      ('汽车', [('f', 'car_crash', '车祸'), ('x', 'seatbelt', '安全带 ’59'), ('f', 'car_crash', '车祸'), ('x', 'airbag', '安全气囊 ’98'), ('s', 'safe_car', '安全')]),
      ('飞机', [('f', 'midair', '空中相撞 ’56'), ('x', 'tower', '空中交通管制'), ('f', 'runway', '跑道相撞 ’77'), ('x', 'crew', '机组培训'), ('s', 'safe_plane', '安全')]),
      ('核电', [('f', 'meltdown', '堆芯熔毁 ’79'), ('x', 'inspect', '安全检查'), ('f', 'meltdown', '切尔诺贝利 ’86'), ('x', 'peer', '同行评审'), ('s', 'safe_plant', '安全')]),
    ],
 ),
}

LINES = {
 'en': [
  ('cover', 'happy', "Hi, I'm Kenji, and this is Capy. Let's walk through the biggest bet people have ever made.", 'HELLO. I AM A VERY CAPABLE CAPYBARA.'),
  ('care', 'idea', 'Three things to know before we start. Tap any one to jump to it.', None),
  ('claim1', 'worried', "The machines are getting better fast, and the safety checks can't keep up.", None),
  ('claim2', 'alarmed', 'It could make life amazing for everyone, or end it for everyone.', None),
  ('claim3', 'puzzled', 'And nobody knows how to make it safe yet, including the people building it.', None),
  ('solution', 'idea', 'So there are two things we have to get right.', None),
  ('1.1', 'idea', 'Guess before you peek at the cards. Most people guess way too high!', 'SAFETY BUDGET: A SLIVER.'),
  ('2.1a', 'happy', 'If this goes right, the prize is huge. Look how fast the economy could grow!', None),
  ('2.1b', 'calm', 'So what would all that growth mean for regular people like us?', None),
  ('2.2a', 'alarmed', 'But the same AI could end everything. There are four ways it could go wrong.', None),
  ('2.2b', 'puzzled', 'Wait, why would an AI take our stuff if nobody told it to?', 'SUBGOAL ADDED: ACQUIRE RESOURCES.'),
  ('2.2c', 'shocked', 'None of these has happened yet. Tap one to see how it could.', None),
  ('2.3a', 'worried', 'With cars and planes, people fixed things after each crash. With AI we might only get one go.', None),
  ('2.3b', 'surprised', 'Reason one: AI is already helping to build better AI.', None),
  ('2.3c', 'sad', "Reason two: once it speeds up, we can't catch up.", 'SPEED: 10,000,000× HUMAN.'),
  ('3.1a', 'serious', 'Everyone wants to win the race, so nobody wants to slow down.', None),
  ('3.1b', 'idea', "Now you're running the lab. What would you do?", None),
  ('3.2a', 'puzzled', "People can't even agree with each other on what they want. So whose wishes should the AI follow?", None),
  ('3.2b', 'worried', 'Handing a job to someone else always comes with this risk, and with AI the stakes are far bigger.', None),
  ('3.2c', 'serious', 'Right now, a handful of companies decide what goes in.', None),
  ('4.1a', 'puzzled', 'Telling an AI what we actually want is much harder than it sounds.', None),
  ('4.1b', 'surprised', 'You get exactly what you asked for, and that is often far from what you meant.', None),
  ('4.1c', 'worried', 'Even a goal worded perfectly can still end badly.', None),
  ('4.1d', 'idea', 'Try it! Pick a goal and see what the machine did with it.', 'OBJECTIVE MET. TECHNICALLY.'),
  ('4.1e', 'alarmed', 'Even if we word it right, the AI might learn a different goal while we train it.', None),
  ('4.1f', 'sad', "We only see what it does. We can't see what it wants.", None),
  ('4.2a', 'worried', "Passing the test used to mean something. Now it doesn't prove much.", None),
  ('4.2b', 'alarmed', 'The smarter the model, the better it gets at gaming our tests.', 'TEST DETECTED. BEHAVING.'),
  ('4.2c', 'serious', "We still can't look inside and check what we built.", None),
  ('5.1a', 'happy', 'Okay, so what are people doing about it? Quite a lot, actually!', None),
  ('5.1b', 'calm', 'Layer one: shape how it behaves while we build it.', None),
  ('5.1c', 'idea', 'Layer two: test it before it goes out the door.', None),
  ('5.1d', 'serious', 'Layer three: keep it contained, in case it turns hostile.', None),
  ('5.1e', 'calm', 'Layer four: rules for the companies building it.', None),
  ('5.1f', 'idea', 'Want the full map? Open these up.', None),
  ('5.2a', 'worried', 'But every layer has cracks.', None),
  ('5.2b', 'sad', 'Right now, none of it reliably holds up in the hard cases.', None),
  ('5.3', 'serious', "So here's what has to change.", None),
  ('5.4a', 'happy', 'And this is where you come in!', 'NEW JOB: TELL A FRIEND.'),
  ('5.4b', 'calm', 'Researchers have a job to do too.', None),
  ('5.4c', 'serious', 'The labs have to slow down and own the risk.', None),
  ('5.4d', 'idea', 'And governments need real rules, wherever you live.', None),
  ('anthem', 'happy', "Thanks for reading with us. Let's stay in touch!", None),
 ],
 'zh': [
  ('cover', 'happy', '你好，我是 Kenji，这是 Capy。我们一起来看看人类有史以来下过的最大一场赌注。', '你好。我是一只非常能干的水豚。'),
  ('care', 'idea', '开始之前，先记住三件事。点任意一张卡片就能跳过去。', None),
  ('claim1', 'worried', '机器进步得飞快，安全检查却跟不上。', None),
  ('claim2', 'alarmed', '它可能让所有人的生活变得美好，也可能让所有人的生活就此结束。', None),
  ('claim3', 'puzzled', '而且至今没人知道怎样让它安全，连造它的人也不知道。', None),
  ('solution', 'idea', '所以，有两件事我们必须做对。', None),
  ('1.1', 'idea', '先猜一猜，再看卡片。大多数人都猜得太高了！', '安全预算：一丁点。'),
  ('2.1a', 'happy', '如果一切顺利，回报大得惊人。看看经济能长得多快！', None),
  ('2.1b', 'calm', '那么，这么多增长，对我们普通人意味着什么？', None),
  ('2.2a', 'alarmed', '可同样的 AI 也可能终结一切。出错的方式有四种。', None),
  ('2.2b', 'puzzled', '等等，没人叫它这么做，AI 为什么要抢我们的东西？', '已新增子目标：获取资源。'),
  ('2.2c', 'shocked', '这些都还没发生过。点开一张，看看它可能怎样发生。', None),
  ('2.3a', 'worried', '汽车和飞机，每出一次事故，人们就改进一次。换成 AI，我们可能只有一次机会。', None),
  ('2.3b', 'surprised', '第一个原因：AI 已经在帮忙造更好的 AI 了。', None),
  ('2.3c', 'sad', '第二个原因：它一旦加速，我们就再也追不上。', '速度：人类的 10,000,000 倍。'),
  ('3.1a', 'serious', '每个人都想赢下这场竞赛，所以没人愿意慢下来。', None),
  ('3.1b', 'idea', '现在由你来管这家实验室。你会怎么做？', None),
  ('3.2a', 'puzzled', '人和人之间都没法就想要什么达成一致。那 AI 该听谁的？', None),
  ('3.2b', 'worried', '把事情交给别人去办，总有这种风险，换成 AI，代价要大得多。', None),
  ('3.2c', 'serious', '眼下，决定往里装什么的，只有寥寥几家公司。', None),
  ('4.1a', 'puzzled', '告诉 AI 我们真正想要什么，比听起来难得多。', None),
  ('4.1b', 'surprised', '你得到的恰好是你说出口的东西，而那常常和你心里想的差得很远。', None),
  ('4.1c', 'worried', '就算目标写得无懈可击，结局也可能很糟。', None),
  ('4.1d', 'idea', '试试看！选一个目标，看看机器拿它做了什么。', '目标已达成。字面上。'),
  ('4.1e', 'alarmed', '就算我们把话说对了，AI 在训练中学到的也可能是另一个目标。', None),
  ('4.1f', 'sad', '我们只看得到它做了什么，看不到它想要什么。', None),
  ('4.2a', 'worried', '以前通过测试还能说明点什么，现在说明不了多少了。', None),
  ('4.2b', 'alarmed', '模型越聪明，就越会钻我们测试的空子。', '检测到测试。表现良好。'),
  ('4.2c', 'serious', '我们至今还没法打开它，检查自己造出了什么。', None),
  ('5.1a', 'happy', '好，那人们在做些什么？其实做了不少！', None),
  ('5.1b', 'calm', '第一层：在建造时就塑造它的行为。', None),
  ('5.1c', 'idea', '第二层：出门之前先测一测。', None),
  ('5.1d', 'serious', '第三层：把它看住，以防它变得有敌意。', None),
  ('5.1e', 'calm', '第四层：给造它的公司立规矩。', None),
  ('5.1f', 'idea', '想看全貌？把这些展开看看。', None),
  ('5.2a', 'worried', '可每一层都有裂缝。', None),
  ('5.2b', 'sad', '眼下，在最难的情况下，没有哪一层靠得住。', None),
  ('5.3', 'serious', '所以，这些必须改变。', None),
  ('5.4a', 'happy', '现在轮到你出场了！', '新任务：告诉一个朋友。'),
  ('5.4b', 'calm', '研究人员也有他们的活要干。', None),
  ('5.4c', 'serious', '实验室必须慢下来，并为风险负责。', None),
  ('5.4d', 'idea', '政府也需要真正的规则，无论你住在哪里。', None),
  ('anthem', 'happy', '谢谢你陪我们读完。保持联系！', None),
 ],
}
