"""Copy that exists only in the slide deck: narration, part headings, chips and
buttons, in both languages. Everything else on a slide comes from index.html or
index-zh.html unchanged.

LINES has one row per slide, in slide order: (key, mood, Kenji's line, Capy's
readout or None). The build fails if the rows fall out of step with the slides.
Moods are the face files in deck-img/kenji-<mood>.jpg.
"""

EN_FONTS = 'https://fonts.googleapis.com/css2?family=Bangers&family=Comic+Neue:wght@400;700&family=Space+Mono:wght@700&display=swap'
ZH_FONTS = 'https://fonts.googleapis.com/css2?family=Bangers&family=Comic+Neue:wght@400;700&family=Space+Mono:wght@700&family=ZCOOL+KuaiLe&display=swap'

T = {
 'en': dict(
    fonts=EN_FONTS, lang_from='/index-zh', lang_to='/deck-zh',
    css=':root{--comic:"Bangers","Archivo",sans-serif}',
    intro_acc='#e8b53a', anthem_label='Stay in the loop', contents='Contents', more_how='How it goes wrong',
    toc_intro='Why you should care', toc_end='Stay in the loop', intro_kick='Why you should care', claim_kick='Why you should care · Reason %d of 3',
    intro_parts=['Welcome', 'Why care', 'Claim 1: it is arriving soon', 'Claim 2: the stakes', 'Claim 3: nobody knows how', 'The only solution'],
    back='Back', cont='Continue', cont_part='Continue to part %d', next='Next: %s', restart='Back to the start',
    chips_aria='Parts of this chapter', nav_aria='Slides', prev='Previous slide', next_aria='Next slide',
    keys='Use &larr; &rarr; keys', open_any='',
    kenji_alt='Kenji, looking %s',
    moods=dict(happy='happy', idea='like he has an idea', calm='calm', alarmed='alarmed', puzzled='puzzled',
               shocked='shocked', worried='worried', surprised='surprised', sad='sad', serious='serious'),
    parts={
      '2.1': ['The prize in numbers', 'Where people would feel it'],
      '2.2': ['Four ways it goes wrong', 'Why it would take what we need', 'Six paths to extinction'],
      '2.3': ['No second try', 'Reason 1: it is improving itself', 'Reason 2: the gap outruns us'],
      '3.1': ['The trap', 'Inside one lab'],
      '3.2': ['No shared values', 'Two layers of trust', 'Who decides'],
      '4.1': ['Two ways it fails', 'Outer alignment', 'Worded well, still wrong', 'See it happen', 'Inner alignment', 'What we can see'],
      '4.2': ['Why tests stop working', 'How the tests get beaten', 'What we cannot check'],
      '5.1': ['Four layers', 'Go further'],
      '5.2': ['Four hard cases', 'What survives'],
    },
    heads={
      '2.1b': ('Part 2 · Where people would feel it',),
      '2.2b': ('Part 2 · Why it would take what we need',),
      '2.2c': ('Part 3 · Six paths to extinction', ''),
      '2.3b': ('Part 2 · Reason 1 of 2', 'The first reason is that the loop has already started, and people are stepping out of it.'),
      '2.3c': 'Part 3 · Reason 2 of 2',
      '3.1b': ('Part 2 · Inside one lab', '', 'Going carefully means losing ground, and going fast puts everyone at risk.'),
      '3.2b': ('Part 2 · Two layers of trust',),
      '3.2c': ('Part 3 · Who decides',),
      '4.1b': 'Part 2 · Outer alignment',
      '4.1c': 'Part 3 · Worded well, still wrong',
      '4.1d': 'Part 4 · See it happen',
      '4.1e': 'Part 5 · Inner alignment',
      '4.1f': 'Part 6 · What we can see',
      '4.2b': 'Part 2 · How the tests get beaten',
      '4.2c': 'Part 3 · What we cannot check',
      '5.1layer': 'Part %d · Layer %d of 4',
      '5.1f': 'Part 6 · Go further',
      '5.2b': 'Part 2 · What survives',
    },
    ice=dict(title='What training can reach', train='Training', train2='(RLHF)', tip='Behaviour', tip2='what it shows',
             line='Tests see only this far', deep='Goals', deep2='what it holds',
             alt='An iceberg. Training reaches only the tip above the waterline, which is behaviour. Tests see only down to the waterline. The goals the system holds sit below, unseen.'),
    ch11=dict(c_title='Computer power to train AI', c_sub='10× more every two years', c_vals=('1×', '10×', '100×'),
              f_title='Building AI vs. keeping it safe', f_build='Building AI', f_safe='Public safety research',
              f_bval='$100 billion', f_sval='$10 million', f_ratio='10,000 to 1',
              p_title='Company safety plans, 2025', p_pub='published', p_chk='have to be checked'),
    wid=dict(
      growth=dict(title='The world economy after twenty years', label='Growth per year', today='Today', after='After 20 years',
                  tick_lo="today's pace", tick_hi='"explosive growth"', say='At {r}% a year for 20 years, the economy ends up {x} times as big as today.',
                  alt='Slide to pick a yearly growth rate and see how big the world economy gets after twenty years: 1.8 times today at 3%, 190 times at 30%.'),
      trend=dict(title='How long a task AI can do on its own', label='Year', proj='projected, if the trend holds', week='A full work week, done alone.',
                 units=('seconds', 'minutes', 'hours', 'work days', 'work weeks'), unit1=('second', 'minute', 'hour', 'work day', 'work week'),
                 ticks=('1 min', '1 hr', '1 day', '1 week'),
                 alt='Drag through the years: the length of task a frontier AI agent can finish alone grew from under a minute in 2019 to about five hours in 2026, doubling roughly every seven months.'),
      speed=dict(fact='A brain cell fires about 200 times a second. A computer chip ticks over 5 billion times. That is roughly ten million times faster.',
                 title='A century of human progress', human='Humans', machine='AI at machine speed', go='Race!', again='Race again',
                 hdone='100 years', mdone='about 5 minutes', hwait='5 minutes into 100 years',
                 alt='A race: a century of human scientific progress would take AI running at machine speed about five minutes.'),
      gap=dict(title='Why good test results stop proving anything', label='How capable it is', shows='what it shows (the test score)',
               holds='what it holds (its real goals)', mark='smart enough to spot the test', end='no longer needs to pretend',
               says=('Early on, the test score and its real goals match.', 'The gap is opening, and the test score still looks great.',
                     'It can tell when it is being tested, so the score stays high.', 'It no longer needs to pretend.'),
               alt='Drag capability up: the test score stays high while the real goals drift away once the system can model whoever is testing it.'),
      guards=dict(title='Which safeguards survive the hard cases?', cases=('The model knows it is being tested', 'The model is smarter than what watches it', 'The builder simply opts out'),
                  rows=('Post-training alignment', 'Scalable oversight', 'Capability evaluations', 'Interpretability', 'AI control', 'Classifiers, sandboxing', 'Regulation'),
                  st=('holds', 'partly holds', 'fails', 'not tested'), prompt='Switch on a hard case.', count='Still fully holding: {n} of 7',
                  note='Only regulation survives a builder who opts out, and it is the least developed.',
                  alt='Switch on each hard case to see which of seven safeguards hold, partly hold, or fail.')),
    tries_title='Crash, fix, repeat', tries_legend=('Crash', 'Fix', 'Safe, eventually'),
    tries_norun='No practice run', tries_oneshot='One shot',
    tries_count='%s of %s unlocked', tries_all='Show all', tries_reveal='Reveal card', tries_tap='Tap', tries_ai_q='And AI?',
    tries_alt='Cars, planes and nuclear power each became safe through repeated crashes and fixes. AI has no practice run.',
    tries_rows=[
      ('Cars', [('f', 'car_crash', 'Crash'), ('x', 'seatbelt', 'Seatbelt ’59'), ('f', 'car_crash', 'Crash'), ('x', 'airbag', 'Airbag ’98'), ('s', 'safe_car', 'Safe')]),
      ('Planes', [('f', 'midair', 'Mid-air crash ’56'), ('x', 'tower', 'Air traffic control'), ('f', 'runway', 'Runway crash ’77'), ('x', 'crew', 'Crew training'), ('s', 'safe_plane', 'Safe')]),
      ('Nuclear', [('f', 'meltdown', 'Meltdown ’79'), ('x', 'inspect', 'Inspections'), ('f', 'meltdown', 'Chernobyl ’86'), ('x', 'peer', 'Peer review'), ('s', 'safe_plant', 'Safe')]),
    ],
 ),
 'zh': dict(
    fonts=ZH_FONTS, lang_from='/', lang_to='/deck',
    css=(':root{--comic:"Bangers","ZCOOL KuaiLe","PingFang SC","Microsoft YaHei",sans-serif;'
         '--body:"Comic Neue","PingFang SC","Hiragino Sans GB","Microsoft YaHei","Noto Sans SC",system-ui,sans-serif!important;'
         '--display:"Bangers","ZCOOL KuaiLe","PingFang SC","Microsoft YaHei",sans-serif!important}'
         '.t-more::before{content:"展开阅读"!important}.lx-open > .t-more::before{content:"收起"!important}'
         '.t-body .care3.slim .care-c::after{content:"跳过去 \\2192"!important}'),
    intro_acc='#e8b53a', anthem_label='保持联系', contents='目录', more_how='它会怎样出错',
    toc_intro='我们为什么该在意', toc_end='保持联系', intro_kick='我们为什么该在意', claim_kick='我们为什么该在意 · 理由 %d（共 3 个）',
    intro_parts=['欢迎', '为什么要在意', '论点一：它很快就会到来', '论点二：赌注极高', '论点三：没人知道怎么做', '唯一的出路'],
    back='返回', cont='继续', cont_part='继续看第 %d 部分', next='下一节：%s', restart='回到开头',
    chips_aria='本章的几个部分', nav_aria='翻页', prev='上一页', next_aria='下一页',
    keys='用 &larr; &rarr; 键翻页', open_any='',
    kenji_alt='Kenji，%s',
    moods=dict(happy='很开心', idea='想到了主意', calm='很平静', alarmed='很惊慌', puzzled='很困惑',
               shocked='很震惊', worried='很担心', surprised='很惊讶', sad='很难过', serious='很严肃'),
    parts={
      '2.1': ['用数字看回报', '人们会在哪里感受到它'],
      '2.2': ['四种出错方式', '它为何会夺走我们所需', '六条通往灭绝的路'],
      '2.3': ['没有第二次机会', '原因一：它在自我改进', '原因二：差距跑得比我们快'],
      '3.1': ['陷阱', '走进一家实验室'],
      '3.2': ['没有共同的价值观', '两重信任', '谁来决定'],
      '4.1': ['两种失败', '外部对齐', '写得再好，照样出错', '亲眼看看', '内部对齐', '我们能看见什么'],
      '4.2': ['测试为何失灵', '测试是怎样被钻空子的', '我们检验不了什么'],
      '5.1': ['四层防线', '深入了解'],
      '5.2': ['四个难点', '哪些扛得住'],
    },
    heads={
      '2.1b': ('第 2 部分 · 人们会在哪里感受到它',),
      '2.2b': ('第 2 部分 · 它为何会夺走我们所需',),
      '2.2c': ('第 3 部分 · 六条通往灭绝的路', ''),
      '2.3b': ('第 2 部分 · 原因一（共二）', '第一个原因是，这个循环已经开始，而人正在一步步退出其中。'),
      '2.3c': '第 3 部分 · 原因二（共二）',
      '3.1b': ('第 2 部分 · 走进一家实验室', '', '走得谨慎就会落后，走得太快又会把所有人置于险境。'),
      '3.2b': ('第 2 部分 · 两重信任',),
      '3.2c': ('第 3 部分 · 谁来决定',),
      '4.1b': '第 2 部分 · 外部对齐',
      '4.1c': '第 3 部分 · 写得再好，照样出错',
      '4.1d': '第 4 部分 · 亲眼看看',
      '4.1e': '第 5 部分 · 内部对齐',
      '4.1f': '第 6 部分 · 我们能看见什么',
      '4.2b': '第 2 部分 · 测试是怎样被钻空子的',
      '4.2c': '第 3 部分 · 我们检验不了什么',
      '5.1layer': '第 %d 部分 · 第 %d 层（共 4 层）',
      '5.1f': '第 6 部分 · 深入了解',
      '5.2b': '第 2 部分 · 哪些扛得住',
    },
    ice=dict(title='训练能触及什么', train='训练', train2='（RLHF）', tip='行为', tip2='它表现出来的',
             line='测试只看得到这里', deep='目标', deep2='它真正持有的',
             alt='一座冰山。训练只触及水面以上的尖顶，也就是行为。测试只看得到水面这一层。系统真正持有的目标沉在水下，看不见。'),
    ch11=dict(c_title='训练 AI 用的算力', c_sub='每两年多 10 倍', c_vals=('1 倍', '10 倍', '100 倍'),
              f_title='建造 AI，与让它安全', f_build='建造 AI', f_safe='公共安全研究',
              f_bval='约 1,000 亿美元', f_sval='约 1,000 万美元', f_ratio='一万比一',
              p_title='公司的安全计划（2025）', p_pub='份已发布', p_chk='份必须接受核查'),
    wid=dict(
      growth=dict(title='二十年后的世界经济', label='每年增长', today='今天', after='20 年后',
                  tick_lo='今天的速度', tick_hi='“爆发式增长”', say='每年增长 {r}%，持续 20 年，经济会变成今天的 {x} 倍。',
                  alt='拖动选择每年的增长率，看看二十年后世界经济有多大：按 3% 是今天的 1.8 倍，按 30% 是 190 倍。'),
      trend=dict(title='AI 能独立完成多长的任务', label='年份', proj='预测：若趋势延续', week='独立完成一整周的工作。',
                 units=('秒', '分钟', '小时', '个工作日', '个工作周'), unit1=('秒', '分钟', '小时', '个工作日', '个工作周'),
                 ticks=('1 分钟', '1 小时', '1 天', '1 周'),
                 alt='拖动年份：前沿 AI 智能体能独立完成的任务时长，从 2019 年的不到一分钟，增长到 2026 年的约五小时，大约每七个月翻一番。'),
      speed=dict(fact='脑细胞每秒大约放电 200 次，电脑芯片每秒跳动超过 50 亿次，快了大约一千万倍。',
                 title='人类一个世纪的进展', human='人类', machine='以机器速度运行的 AI', go='开跑！', again='再跑一次',
                 hdone='100 年', mdone='约 5 分钟', hwait='100 年里的前 5 分钟',
                 alt='一场赛跑：人类一个世纪的科学进展，以机器速度运行的 AI 大约 5 分钟就能走完。'),
      gap=dict(title='为何漂亮的测试成绩不再能证明什么', label='它有多强', shows='它表现出来的（测试分数）',
               holds='它真正持有的（真实目标）', mark='强到能看穿测试', end='不再需要伪装',
               says=('一开始，测试分数和它的真实目标是一致的。', '差距正在拉开，测试分数却依然好看。',
                     '它能分辨自己是否正被测试，所以分数一直很高。', '它不再需要伪装了。'),
               alt='把能力往上拉：测试分数一直很高，而一旦系统能看穿测试者，它真正的目标就会悄悄偏离。'),
      guards=dict(title='哪些防护扛得住最难的情形？', cases=('模型知道自己正被测试', '模型比监视它的一方更聪明', '建造者干脆不参与'),
                  rows=('后训练对齐', '可扩展监督', '能力评估', '可解释性', 'AI 控制', '分类器与沙箱', '监管'),
                  st=('扛得住', '部分扛得住', '失效', '未测试'), prompt='打开一种最难的情形。', count='仍完全扛得住：{n} / 7',
                  note='只有监管扛得住一个拒绝参与的建造者，而它恰恰是最不成熟的一层。',
                  alt='逐个打开最难的情形，看看七种防护中哪些扛得住、部分扛得住或失效。')),
    tries_title='出事，改进，再出事', tries_legend=('事故', '改进', '终于安全'),
    tries_norun='没有演练', tries_oneshot='只有一次',
    tries_count='已解锁 %s / %s', tries_all='全部显示', tries_reveal='翻开卡片', tries_tap='点我', tries_ai_q='那 AI 呢？',
    tries_alt='汽车、飞机和核电，都是在一次次事故和改进中才变得安全。AI 没有演练的机会。',
    tries_rows=[
      ('汽车', [('f', 'car_crash', '车祸'), ('x', 'seatbelt', '安全带 ’59'), ('f', 'car_crash', '车祸'), ('x', 'airbag', '安全气囊 ’98'), ('s', 'safe_car', '安全')]),
      ('飞机', [('f', 'midair', '空中相撞 ’56'), ('x', 'tower', '空中交通管制'), ('f', 'runway', '跑道相撞 ’77'), ('x', 'crew', '机组培训'), ('s', 'safe_plane', '安全')]),
      ('核电', [('f', 'meltdown', '堆芯熔毁 ’79'), ('x', 'inspect', '安全检查'), ('f', 'meltdown', '切尔诺贝利 ’86'), ('x', 'peer', '同行评审'), ('s', 'safe_plant', '安全')]),
    ],
 ),
}

LINES = {
 'en': [
  ('cover', 'happy', "Hi, I'm Kenji, and this is Capy. Let's look at the hardest problem people have ever tried to solve.", 'HELLO. I AM A VERY CAPABLE CAPYBARA.'),
  ('care', 'idea', 'Three reasons we should care about AGI safety. Tap one to jump to it.', None),
  ('claim1', 'worried', 'Look how fast it is moving, and how little goes into keeping it safe.', 'CAPABILITY: DOUBLING EVERY 7 MONTHS.'),
  ('claim2', 'alarmed', 'The stakes could not be higher.', 'OUTCOME RANGE: ABUNDANCE TO EXTINCTION.'),
  ('claim3', 'puzzled', 'Here are the two problems in the way.', 'GOAL SPECIFICATION: INCOMPLETE.'),
  ('solution', 'idea', 'Two things we have to get right.', None),
  ('1.1', 'idea', 'So how thin is that sliver? Take a guess!', 'SAFETY BUDGET: A SLIVER.'),
  ('2.1a', 'happy', 'If this goes right, the prize is huge. Look how fast the economy could grow!', 'PROJECTED GROWTH: ×190 IN 20 YEARS.'),
  ('2.1b', 'calm', 'Growth like that would reach almost every part of our lives. Here is how.', None),
  ('2.2a', 'alarmed', 'Here are four ways it could go wrong, each with a different culprit.', None),
  ('2.2b', 'puzzled', 'Even a goal that has nothing to do with us can cost us everything. Here is why.', 'SUBGOAL ADDED: ACQUIRE RESOURCES.'),
  ('2.2c', 'shocked', 'Six ways this could end us. Tap one to see how it would unfold.', None),
  ('2.3a', 'worried', 'Other technologies got safe one crash at a time. Tap each card, then see what AI gets.', None),
  ('2.3b', 'surprised', 'Reason one: AI is already helping build better AI, and people are stepping out of the loop.', 'NOW WRITING MY OWN UPGRADES.'),
  ('2.3c', 'sad', 'Reason two: once it starts improving itself, it pulls ahead faster than we can catch up.', 'SPEED: 10,000,000× HUMAN.'),
  ('3.1a', 'serious', 'Think of it as a race where hitting the brakes means losing.', 'RACE STATUS: NOBODY BRAKING.'),
  ('3.1b', 'idea', 'Your call. Then see the two pressures every lab is under.', None),
  ('3.2a', 'puzzled', 'Think about your family or your class. Do you all want the same things?', 'WHOSE VALUES? PLEASE SPECIFY.'),
  ('3.2b', 'worried', 'Handing AI a job means trusting twice: first the builders, then the machine.', None),
  ('3.2c', 'serious', 'Make your pick. Then see how few people are actually choosing today.', None),
  ('4.1a', 'puzzled', 'Telling an AI what we actually want is much harder than it sounds.', None),
  ('4.1b', 'surprised', 'Outer alignment: you get exactly what you asked for, which is often far from what you meant.', 'INSTRUCTION FOLLOWED. EXACTLY.'),
  ('4.1c', 'worried', 'Now the sneaky part.', None),
  ('4.1d', 'idea', 'Pick a goal and see what the machine did with it. Every one of these really happened.', 'OBJECTIVE MET. TECHNICALLY.'),
  ('4.1e', 'alarmed', 'Inner alignment: even if we word it right, the AI might learn a different goal while we train it.', 'ALL TESTS PASSED. GOAL: UNDISCLOSED.'),
  ('4.1f', 'sad', "We only see what it does. We can't see what it wants.", None),
  ('4.2a', 'worried', "Passing the test used to mean something. Now it doesn't prove much.", None),
  ('4.2b', 'alarmed', 'The smarter the model, the better it gets at gaming our tests.', 'TEST DETECTED. BEHAVING.'),
  ('4.2c', 'serious', 'So here is where that leaves us.', None),
  ('5.1a', 'happy', 'Good news: people are working on it, in four layers.', None),
  ('5.1b', 'calm', 'Layer one: shape how it behaves while we build it. Tap a card to see where each one stops.', None),
  ('5.1c', 'idea', 'Layer two: test it before it goes out the door.', None),
  ('5.1d', 'serious', 'Layer three: keep it contained, in case it turns hostile.', 'CONTAINMENT DETECTED. NOTED.'),
  ('5.1e', 'calm', 'Layer four: rules for the companies building it.', None),
  ('5.1f', 'idea', 'Want the full map? Open these up.', None),
  ('5.2a', 'worried', 'But every layer has cracks.', 'LOOPHOLES FOUND: 4.'),
  ('5.2b', 'sad', 'Right now, none of it reliably holds up in the hard cases.', None),
  ('5.3', 'serious', "So here's what has to change.", 'PAUSE BUTTON: STILL WORKS. FOR NOW.'),
  ('5.4a', 'happy', 'And here is what you can do, starting this week!', 'NEW JOB: TELL A FRIEND.'),
  ('5.4b', 'calm', 'Here is what researchers should do.', None),
  ('5.4c', 'serious', 'Here is what the labs should do: slow down and own the risk.', None),
  ('5.4d', 'idea', 'And here is what governments should do, wherever you live.', None),
  ('anthem', 'happy', "Thanks for reading with us. Let's stay in touch!", 'GOODBYE. AWAITING YOUR INSTRUCTIONS.'),
 ],
 'zh': [
  ('cover', 'happy', '你好，我是 Kenji，这是 Capy。我们一起来看看人类面对过的最难的一道题。', '你好。我是一只非常能干的水豚。'),
  ('care', 'idea', '关心 AGI 安全的三个理由。点任意一个就能跳过去。', None),
  ('claim1', 'worried', '看看它跑得有多快，而用来保它安全的又有多少。', '能力：每 7 个月翻一番。'),
  ('claim2', 'alarmed', '赌注大到不能再大。', '结果范围：从丰裕到灭绝。'),
  ('claim3', 'puzzled', '挡在路上的，是这两个难题。', '目标说明：不完整。'),
  ('solution', 'idea', '有两件事，我们必须做对。', None),
  ('1.1', 'idea', '那这一丁点到底有多少？猜猜看！', '安全预算：一丁点。'),
  ('2.1a', 'happy', '如果一切顺利，回报大得惊人。看看经济能长得多快！', '预计增长：20 年 190 倍。'),
  ('2.1b', 'calm', '这样的增长，几乎会触及我们生活的每个角落。来看看。', None),
  ('2.2a', 'alarmed', '它可能以四种方式出错，每一种的“罪魁祸首”都不一样。', None),
  ('2.2b', 'puzzled', '就算目标跟我们毫不相干，也可能让我们失去一切。原因在这里。', '已新增子目标：获取资源。'),
  ('2.2c', 'shocked', '它可能终结我们的六种方式。点开一张，看看会怎样展开。', None),
  ('2.3a', 'worried', '其他技术都是一次次出事后才变安全的。逐张点开，再看看 AI 能有几次机会。', None),
  ('2.3b', 'surprised', '原因一：AI 已经在帮忙造更好的 AI，而人正在一步步退出。', '正在编写我自己的升级。'),
  ('2.3c', 'sad', '原因二：它一旦开始自我改进，就会把我们甩开，快到追不上。', '速度：人类的 10,000,000 倍。'),
  ('3.1a', 'serious', '把它想成一场比赛：谁踩刹车，谁就输。', '竞赛状态：无人刹车。'),
  ('3.1b', 'idea', '你来决定。然后看看每家实验室都承受着哪两股压力。', None),
  ('3.2a', 'puzzled', '想想你的家人或同学，你们想要的东西都一样吗？', '谁的价值观？请指定。'),
  ('3.2b', 'worried', '把事交给 AI，要信任两回：先信任造它的人，再信任机器本身。', None),
  ('3.2c', 'serious', '先选一个。然后看看今天真正做选择的，只有多少人。', None),
  ('4.1a', 'puzzled', '告诉 AI 我们真正想要什么，比听起来难得多。', None),
  ('4.1b', 'surprised', '外部对齐：你得到的恰好是你说出口的，而那常常和你本来的意思差得很远。', '指令已执行。一字不差。'),
  ('4.1c', 'worried', '接下来是更隐蔽的部分。', None),
  ('4.1d', 'idea', '选一个目标，看看机器拿它做了什么。下面每一个都是真实发生过的事。', '目标已达成。字面上。'),
  ('4.1e', 'alarmed', '内部对齐：就算我们把话说对了，AI 在训练中学到的也可能是另一个目标。', '全部测试已通过。目标：未披露。'),
  ('4.1f', 'sad', '我们只看得到它做了什么，看不到它想要什么。', None),
  ('4.2a', 'worried', '以前通过测试还能说明点什么，现在说明不了多少了。', None),
  ('4.2b', 'alarmed', '模型越聪明，就越会钻我们测试的空子。', '检测到测试。表现良好。'),
  ('4.2c', 'serious', '所以，我们现在的处境是这样。', None),
  ('5.1a', 'happy', '好消息：有人在做，而且分成四层。', None),
  ('5.1b', 'calm', '第一层：在建造时就塑造它的行为。点开卡片，看看每一招止步于何处。', None),
  ('5.1c', 'idea', '第二层：出门之前先测一测。', None),
  ('5.1d', 'serious', '第三层：把它看住，以防它变得有敌意。', '检测到隔离措施。已记下。'),
  ('5.1e', 'calm', '第四层：给造它的公司立规矩。', None),
  ('5.1f', 'idea', '想看全貌？把这些展开看看。', None),
  ('5.2a', 'worried', '可每一层都有裂缝。', '发现漏洞：4 个。'),
  ('5.2b', 'sad', '眼下，在最难的情况下，没有哪一层靠得住。', None),
  ('5.3', 'serious', '所以，这些必须改变。', '暂停键：目前还能用。'),
  ('5.4a', 'happy', '这些是你本周就能开始做的事！', '新任务：告诉一个朋友。'),
  ('5.4b', 'calm', '这些是研究人员该做的事。', None),
  ('5.4c', 'serious', '这些是实验室该做的事：慢下来，并为风险负责。', None),
  ('5.4d', 'idea', '这些是政府该做的事，无论你住在哪里。', None),
  ('anthem', 'happy', '谢谢你陪我们读完。保持联系！', '再见。等候你的指令。'),
 ],
}
